### ISSUE TITLE
Readme/wiki not reflecting current state

### ISSUE THREAD

**Issue by yohny** [ERNICommunity/AgentMulder#12]
Hi,
you should update the project's Readme to reflect the current state of the product. The last sections
`We hope to have something for you to download soon. In the meantime,..
Please note: we are in the process of sorting the details out with the original author...` are no longer valid I believe.
Also the wiki seems like the project is just freshly revived, yet it is already published in Resharper's extension gallery.

**Comment by mareklinka** [comment]
I've been meaning to do this this week but workload wasn't cooperating. I'll do it on the weekend.

**Comment by mareklinka** [comment]
Wiki and readme.md updated with the latest info and a link to the R# Gallery.
