### ISSUE TITLE
extension might add tabs to code somehow

### ISSUE THREAD

**Issue by eOkadas** [ERNICommunity/AgentMulder#18]
Hi, 

this might be unrelated, but I had an issuer with resharper where it would add tabs between method names and parentheses like so :
```C#
Thing.Wait     ();
var stuff    = new Stuff    ();
```

and no amount of setting reset solved it. Only removing Agent Mulder cured Resharper. I re added it, worked a bit and sure enough the bug was back. I removed it again, problem solved again. I was hesitant to post this but, well, just to let you know.   
It might be a jetbrains issue rather than your extension though.

**Comment by mareklinka** [comment]
Yes, we observe similar issue with certain solutions. So far I haven't been able to pinpoint this. We'll take a look. For me personally, it almost always happens with a fresh .NET Core project, but worked without any issues on a commercial .NET Core project I'm working on. It's rather inconsistent.

I'll try and investigate when I have some time.

**Comment by eOkadas** [comment]
I did switch that project to .NET Core. But I was on a fresh machine so I didn't link the issue to the project type. Okay then.  I'll keep monitoring the page to see if a release fixes that. Thank you for your response.

**Comment by mareklinka** [comment]
Very late response, but we did some fixes in the internals of Mulder and it should have resolved the issue. If you would be willing, could you give the latest release a try? (2018.1.0 went live earlier today)

**Comment by eOkadas** [comment]
No issue that I can see. I'll stick with it for a few days before celebrating 🙏 
If I don't run back to close this issue or comment again this month, I think you can feel free to close it on your end.

**Comment by mareklinka** [comment]
Awesome :) Great news, keep us posted if there are still issues and thanks for the confirmation.

**Comment by NLI-KelbyHunt** [comment]
I can also confirm I used to have this issue and **no longer with 2018.1.0** of the extension.

Thank you @mareklinka & ERNICommunity

**Comment by mareklinka** [comment]
Awesome to get another confirmation. Thanks, everyone, I'm closing the this for now. If you encounter the problem again, please open a new issue.
