### ISSUE TITLE
ReSharper and AgentMulder versioning 

### ISSUE THREAD

**Issue by square-unit** [ERNICommunity/AgentMulder#23]
Hi All,

I'm support engineer of ReSharper team. The latest AgentMulder version seems to support 2017.2.1 but not the newer versions. It breaks R# being installed into R# 2017.3.x (not sure about 2017.2.2).

The supported R# versions haven't been specified in the current AgentMulder version. It is declared as compatible with all the newer versions above R# 2017.2. So it was available in R# Extension Manager despite it can't be installed into more recent versions or can break the R# installation itself.

We removed the extension from the ReSharper Gallery. Please fix the versioning issue and upload the updated version with properly specified supported R# versions. It will become available in the Extension Manager of all the compatible R# builds.

--
Andrey Simukov
Support Engineer
JetBrains
http://www.jetbrains.com
The Drive To Develop
andrey.simukov@jetbrains.com

**Comment by mareklinka** [comment]
Hm, I'll investigate this. Thanks for letting us know.

**Comment by mareklinka** [comment]
I just published a Wave 11-compatible version of the package and marked it's dependencies as Wave [11.0, 12.0). This should make it only visible to R# 2017.3.x, as far as I understand it, right? I also marked the upload as listed in search.

If you still see issues with the versioning, let us know.

**Comment by square-unit** [comment]
> This should make it only visible to R# 2017.3.x, as far as I understand it, right?

Yes. Thank you!
