### ISSUE TITLE
DryIoC Support

### ISSUE THREAD

**Issue by emdadgar2** [ERNICommunity/AgentMulder#24]
Hi,
Are you planning on adding [DryIOC](https://bitbucket.org/dadhi/dryioc) support?

Thanks

**Comment by pavolbelusko** [comment]
Hello,

we are not planning to add support for DryIOC, however we welcome and are open to pull requests.

**Comment by mareklinka** [comment]
I started looking into the DryIOC container support. The container itself is not too different from the others we already support, but the public registration interface is rather convoluted (especially the `RegisterMany` method).

The initial support will therefore be rather limited: we will support the `Register`, `Register<T>`, `RegisterDelegate`, and `RegisterDelegate<T>` methods.
