### ISSUE TITLE
Support for Resharper 2018

### ISSUE THREAD

**Issue by SebastianAtWork** [ERNICommunity/AgentMulder#25]
Hi, i really like the idea of AgentMulder, but i cant find it in the Extensions Tab.
Could it be that it does not get listed because its not compatible with Resharper 2018? (I have 2018.1)

**Comment by pavolbelusko** [comment]
Hello, we are happy that You find Mulder useful. As You say, the new ReSharper is not supported yet. However we plan to update it. Stay tuned.

**Comment by gregsdennis** [comment]
I, too, would like to see this extension support 2018 and future versions!
