### ISSUE TITLE
ReSharper 2019.3 support

### ISSUE THREAD

**Issue by matkoch** [ERNICommunity/AgentMulder#45]
Do you need help updating to 2019.3 ? We could also introduce support for Rider at the same time, but it would require a few project structure changes.

**Comment by mareklinka** [comment]
I think we should be good but my current work situation changed slightly. I will try and find the time to update. Thanks for the reminder 👍

**Comment by mareklinka** [comment]
Alright, it took a while to get there but the plugin version for 2019.3 is out and being reviewed. Should show up in the gallery soon.
