### ISSUE TITLE
Collection was modified exception

### ISSUE THREAD

**Issue by Demivan** [ERNICommunity/AgentMulder#7]
`RegisteredTypeCollector` and `PatternManagerCache` in method `ICache.SyncUpdate` loop over `dirtyFiles` and call `ICache.Merge` method.
`ICache.Merge` is removing item from `dirtyFiles` collection causing "Collection was modified" exception.

**Comment by mareklinka** [comment]
Interesting. We will investigate. Should be an easy fix. We are planning to update for R# 2017.1 on Monday, we will try and handle this one as well.\

Thanks for the report.
