### ISSUE TITLE
Publish to ReSharper plugins

### ISSUE THREAD

**Issue by olsh** [ERNICommunity/AgentMulder#8]
Are you going to publish the plugin to ReSharper plugins?
Thank you for the work!

**Comment by mareklinka** [comment]
Yes, that is definitely planned. We now have a working prototype for R# 2017.1 and that should be the version we will publish. However, we are currently in the process of finalizing the transition with the original author of the plugin. We currently don't know when this could be done, but as soon as we have everything in order, the plugin will be published.

**Comment by olsh** [comment]
> We now have a working prototype for R# 2017.1 and that should be the version we will publish.

Yeah, I've built the version from the branch. Works for me. 👍 

> However, we are currently in the process of finalizing the transition with the original author of the plugin.

I've just talked with @hmemcpy and he said that he provided all credentials to you.
Let me know if I can help you somehow.

**Comment by mareklinka** [comment]
Ah, awesome,then. I'll need to sync up with a colleague, I'll get back to you.

**Comment by mareklinka** [comment]
So latest update is: we will try to push the 2017.1 release into the JetBrains repository this week. I'll update the thread when it's done.

**Comment by mareklinka** [comment]
Agent Mulder 2017.1 was officially published to the JetBrains repository yesterday. The published version was built from the Wave 8 branch, without the two Navigate to... providers (we suspect they may be affecting performance). The branch is now pending PR into develop.
